// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlNZ96SZiJrKhwrAYml_0LnsNAGTXCALg',
    appId: '1:796888873984:web:30d3844225cd10194aace5',
    messagingSenderId: '796888873984',
    projectId: 'notif-84302',
    authDomain: 'notif-84302.firebaseapp.com',
    storageBucket: 'notif-84302.appspot.com',
    measurementId: 'G-96KMJSMCKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkMjBzmm-xaO0MvwH72DPUest_JGooOwE',
    appId: '1:796888873984:android:2ffd224e79cec2854aace5',
    messagingSenderId: '796888873984',
    projectId: 'notif-84302',
    storageBucket: 'notif-84302.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPyjIcEqQJI7Mx4zI7lg7ibncebdsH8-o',
    appId: '1:796888873984:ios:01d28ba468b6e9394aace5',
    messagingSenderId: '796888873984',
    projectId: 'notif-84302',
    storageBucket: 'notif-84302.appspot.com',
    iosBundleId: 'com.example.notif',
  );
}
